### ISSUE TITLE
Convert to "CPS"

### ISSUE THREAD

**Issue by inexorabletash** [inexorabletash/jslogo#21]
Make procedure calls async. Simple procedures would be implemented via this transform:

```js
// old
function sum(a, b) {
  return a + b;
}
function div(a, b) {
  if (b === 0)
    throw new Error("Division by zero");
  return a / b;
}

// new
function sum(_, a, b) {
  _(a + b);
}
function div(a, b) {
  if (b === 0)
    _(undefined, new Error("Division by zero");
  _(a / b);
}
```

Task list:
- [ ] Sort out the continuation API - `_(result, error)` or `_.result(r)` and `_.error(e)` or ...?
- [ ] Convert tests to be async - have assert_foo() push a promise onto a stack or something; shim `interpreter.run()` calls with a setTimeout() for now
- [ ] Get the page working with shimmed async `interpreter.run()`
- [ ] Push the shim into the interpreter itself
- [ ] Have `def()` make all the built-in first-order functions async
- [ ] Plumb continuations through evaluation functions
- [ ] Tackle the higher order functions
- [ ] Change any `prompt()` calls to use HTML UI instead of blocking browser UI
- [ ] Add a timeout to drawing operations

**Comment by ianb** [comment]
I was thinking about this a little, as I've been thinking about things like:

```
ONCLICK [SETXY :X :Y] ; dynamic scoping FTW!
```

and this would be much easier with async execution of everything, and a kind of implicit multitasking.

My thought would be to use a hybrid promise approach, where functions could return promises or concrete values.  I converted some sync code to async recently this way and it was surprisingly workable.  It keeps the call signatures the same, and puts most of the work in the expression executor instead of spreading it around too much.

Another option is to use Babel and async await to handle the twistiness of the code.

Maintaining dynamic scoping through this refactoring could be really hard though.

**Comment by inexorabletash** [comment]
Yeah, now that I'm Promise-savvy I agree that's a better route forward, either directly or via Babel/Traceur. I wouldn't mix return types - procs should always return Promises, even if the result is known synchronously. But a helper for writing simple definitions would be fine.

I haven't had cycles to dedicate to this work, but I'm happy to review changes.

**Comment by ianb** [comment]
The hybrid approach seems appealing to me because of the primitives.  For instance:

```javascript
function butfirst(list) {
  return Promise((resolve, reject) => {
    resolve(list.slice(1));
  });
}
function otherButfirst(list) {
  return list.slice(1);
}
```

There's a ton of these non-blocking functions, and forcing them to return promises seems tedious.  But I'd imagine user functions would always return promises, and of course anything that calls arbitrary functions needs to be able to receive promises.

It did occur to me "what if every VALUE could be a promise?"  That is, when we evaluate `BUTFIRST GETSOMEVALUE` we don't force the `GETSOMEVALUE` promise to resolve, but instead require `BUTFIRST` to do that.  I thought there was a name for that concurrency approach (like in [Oz](https://en.wikipedia.org/wiki/Oz_(programming_language)#Dataflow_variables_and_declarative_concurrency)), but now I don't see any name.  Of course you can't really pass the promise around, instead it's a wrapper that both resolves and remembers the value it has resolved, to, so you could still reuse the value (as in `MAKE "a GETSOMEVALUE TYPE :a TYPE BUTFIRST :a`).  But now I'm just brainstorming silly ideas.

**Comment by inexorabletash** [comment]
Calling this "done" c/o 344dae991ff8203068601d06ca246a4659db9bc5

**Comment by ianb** [comment]
Woohoo!
